version: '3.1'

services:
  main-storage:
    image: postgres:alpine3.19 
    restart: always
    ports: 
      - 5432:5432
    volumes:
      - main-storage:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: messages
      POSTGRES_USER: messages
      POSTGRES_DB: messages
  
volumes:
  main-storage:
