version: '3.1'

services:
  main-storage:
    image: postgres:alpine3.19 
    restart: always
    ports: 
      - 5432:5432
    volumes:
      - main-storage:/var/lib/postgresql/data
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: <fill this>
      POSTGRES_USER: <fill this>
      POSTGRES_DB: <fill this>
  messages:
    image: messages
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes: 
    - ./config.deploy.yaml:/etc/messages/config.yaml
    environment:
      MESSAGES_CONF: "/etc/messages/config.yaml"
    ports:
      - 9096:8080
    depends_on:
      - main-storage
  
volumes:
  main-storage:
